# Generated by Django 5.1.1 on 2024-09-08 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_first_name_nonprofit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofit',
            name='type',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='nonprofit',
            name='website',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
