# Generated by Django 5.1.1 on 2024-09-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_nonprofit_type_nonprofit_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonprofit',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
