# Generated by Django 5.1.1 on 2024-09-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_nonprofit_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofit',
            name='donation_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonprofit',
            name='newspaper_signup',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nonprofit',
            name='volunteer_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
