# Generated by Django 5.1.1 on 2024-10-06 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_nonprofit_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonprofit',
            name='description',
        ),
    ]
