# Generated by Django 5.1.2 on 2024-10-22 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_nonprofit_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonprofit',
            name='rank',
            field=models.IntegerField(default=999, max_length=20),
        ),
    ]
