# Generated by Django 5.1.2 on 2024-10-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_nonprofit_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonprofit',
            name='rank',
            field=models.IntegerField(default=999),
        ),
    ]
