# Generated by Django 5.1.3 on 2024-12-30 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_rank_nonprofit_popularity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nonprofit',
            old_name='popularity',
            new_name='rank',
        ),
        migrations.AlterField(
            model_name='nonprofit',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
